name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to PI
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.SSH_KEY }}
          port: 22
    script: |
      bash -l -c "
        cd ~/app/rubee-site

        # Tell Git to ignore changes to files you want to protect
        git update-index --assume-unchanged db/production.db db/structure.rb

        # Abort any existing merge/rebase
        git merge --abort || true
        git rebase --abort || true

        # Stash any other changes
        git stash --include-untracked

        # Pull with rebase (respects assume-unchanged)
        git pull origin main --rebase

        # Reapply any stashed local changes
        git stash pop || true

        # Continue with deployment
        chmod +x ./deploy.sh
        ./deploy.sh
      "
