- name: Deploy
  uses: appleboy/ssh-action@v1.0.3
  with:
    host: ${{ secrets.HOST }}        # ✅ No slashes
    username: ${{ secrets.USER }}                 # ✅ Your Pi's user
    key: ${{ secrets.SSH_KEY }}  # ✅ Your GitHub secret
    port: 22                       # ✅ Must be a valid number
    script: |
      cd ~/rubee
      git pull origin main
      chmod +x ./deploy.sh
      ./deploy.sh

