name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to PI
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.SSH_KEY }}
          port: 22
          script: |
            bash -l -c "
              cd ~/app/rubee-site
              cat .gitignore | grep -v '^#' | while read file; do
                git update-index --assume-unchanged "$file"
              done
              git pull origin main --rebase
              chmod +x ./deploy.sh
              ./deploy.sh
            "


