name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to PI
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.SSH_KEY }}
          port: 22
          script: |
            bash -l -c "
              cd ~/app/rubee-site

              # Silently ignore merge/rebase cleanup if not in progress
              git merge --abort 2>/dev/null || true
              git rebase --abort 2>/dev/null || true

              # Avoid tracking changes to ignored files if they exist
              [ -f db/production.db ] && git update-index --assume-unchanged db/production.db || echo 'Skipping db/production.db'
              [ -f db/structure.rb ] && git update-index --assume-unchanged db/structure.rb || echo 'Skipping db/structure.rb'

              # Stash local changes
              git stash --include-untracked

              # Pull latest from main
              git pull origin main --rebase

              # Try to apply stashed changes back
              git stash pop || true

              # Deploy
              chmod +x ./deploy.sh
              ./deploy.sh
            "
