name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to PI
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.SSH_KEY }}
          port: 22
          script: |
            bash -l -c "
              cd ~/app/rubee-site

              # backup database outside the project (e.g. home directory)
              cp db/production.db ~/production.db.bak || echo 'no db/production.db to back up'

              # Clean repo and override all local changes
              git fetch origin
              git reset --hard origin/main
              git clean -fd  # remove untracked files and folders

              # Restore the database
              mv ~/production.db.bak db/production.db || echo 'No backup found to restore'
              # Deploy
              chmod +x ./deploy.sh
              ./deploy.sh
            "
